# Generated by Django 4.0.5 on 2022-07-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patrones',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=30)),
                ('seccion', models.CharField(max_length=30)),
                ('algoritmo', models.CharField(max_length=30)),
                ('comentarios', models.CharField(max_length=100, null=True)),
                ('usuario', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
